#ifndef __ERRORS_H__
#define __ERRORS_H__

#define SCAN_ERROR 1
#define NUM_COMMAND_ERROR 2
#define SCAN_ROWS_ERROR 3
#define NUM_ROWS_ERROR 4
#define SCAN_COLUMNS_ERROR 5
#define NUM_COLUMNS_ERROR 6
#define ALLOCATE_MATRIX_ERROR 7
#define SCAN_MODE_ERROR 8
#define MODE_ERROR 9
#define SCAN_PERC_ERROR 10
#define PERC_ERROR 11
#define SCAN_MATRIX_ERROR 12
#define SCAN_NONZERO_ELEMS_ERROR 13
#define NONZERO_ELEMS_ERROR 14
#define SCAN_ELEM_ERROR 15
#define ZERO_ELEM_ERROR 16
#define SCAN_STR_ERROR 17
#define STR_ERROR 18
#define SCAN_COL_ERROR 19
#define COL_ERROR 20
#define EMPTY_MATRIX_ERROR 21
#define DIFFERENT_SIZE_ERROR 22
#define ALLOCATE_NONZERO_ELEMS_ERROR 23
#define ALLOCATE_COLUMNS_ERROR 24
#define ALLOCATE_LIST_ERROR 25
#define VALUE_ERROR 26
#define SCAN_ELEMS_IN_ROW_ERROR 27
#define ELEMS_IN_ROW_ERROR 28
#define MALLOC_ERROR 29
#define CALLOC_ERROR 30
#define REPEAT_FILL_ERROR 31

#endif // __ERRORS_H__