#ifndef __ERRORS_H__
#define __ERRORS_H__

#define STACK_SIZE 100000
#define RANDOM_CONST 30
#define NUM_RUNS 100

#define SCAN_METHOD_ERROR 1
#define VALUE_METHOD_ERROR 2
#define SCAN_ACTION_ERROR 3
#define VALUE_ACTION_ERROR 4
#define SCAN_NUM_ELEMS_ERROR 5
#define VALUE_NUM_ELEMS_ERROR 6
#define OVERFLOW_ERROR 7
#define SCAN_ELEM_ERROR 8
#define MALLOC_ERROR 9
#define REALLOC_ERROR 10

#endif // __ERRORS_H__